#! /bin/bash

### BEGIN INIT INFO
# Provides: vncboot
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start VNC Server at boot time
# Description: Start VNC Server at boot time.
### END INIT INFO

# /etc/init.d/vncboot

USER=pi
HOME=/home/pi

export USER HOME

case "$1" in
    start)
        echo "Starting TightVNC Server"
        #Insert your favoured settings for a TightVNC session
        su $USER -c "/usr/bin/tightvncserver :1 -geometry 1280x800 -depth 24"
        ;;

    stop)
        echo "Stopping VNC Server"
        su $USER -c "/usr/bin/tightvncserver -kill :1"
        ;;

    *)
        echo "Usage: /etc/init.d/tightvnc {start|stop}"
        exit 1
        ;;
esac

exit 0
